# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

env:
  PROJECT: test2
  APP_NAME: myapp

jobs:
  build:
    name: Setup and Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '4.3'
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}
        parameters: '{"apitoken": "${{ secrets.CRC_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc project ${PROJECT}
          oc new-app ${GITHUB_WORKSPACE} --name ${APP_NAME}
    - name: Execute oc commands
      run: |
        oc version
        oc expose svc/${{ env.APP_NAME }}

        
